### ISSUE TITLE
Dismiss Keyboard

### ISSUE THREAD

**Issue by rjpalermo1** [mmazzarolo/react-native-login-animation-example#2]
Hi, thank you very much for putting this together.  I am trying to rebuild an obj-c project in react and new, so forgive me asking if obvious or I should know but....

How do you dismiss the keyboard?

I tried wrapping in a scrollview and also tried touchableWithoutFeedback on the index View without any luck.

**Comment by rjpalermo1** [comment]
OK - kept trying and got it working...

in AuthScreen index.js imported TouchableWithoutFeedback in native-react 

```
     ...
    return (

      <TouchableWithoutFeedback onPress={()=>{Keyboard.dismiss()}}>

      <View style={styles.container}>
            <Image
             ...
     </TouchableWithoutFeedback>
```

**Comment by mmazzarolo** [comment]
Glad you find a workaround! 
I'm closing the issue, feel free to open another one if needed!
