### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

### ISSUE THREAD

**Issue by Hemantsolanki103** [mmazzarolo/react-native-login-animation-example#3]
Hi,
Please help me to resolved the issues.

undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

React Detail:
react-native-cli: 2.0.1
react-native: 0.44.0

Thanks,

**Comment by mmazzarolo** [comment]
Hey @Hemantsolanki103, this animation was just a simple demo, so I'm sorry but I cannot keep it compatible with the newer react-native versions.  
P.S.: It will work if you'll use the dependencies described in the package.json of this repo though.
