### ISSUE TITLE
Upgrade latest PropTypes

### ISSUE THREAD

**Issue by rjpalermo1** [mmazzarolo/react-native-login-animation-example#4]
You can upgrade you package with the and replace all the PropTypes imports from react to it's own module now according to https://reactjs.org/docs/typechecking-with-proptypes.html

I did a create-react-app latest (0.49), added your files and updated the imports and it launched right up.

**Comment by mmazzarolo** [comment]
Hey @rjpalermo1, thanks for the info, but since this repo is simply a "showcase" of the animation I'm not keeping up to the date with the future releases of React-Native.
