### ISSUE TITLE
invariant violation element type is invalid expected a string (for built-in components) or a class /function (for composite components) but got: object

### ISSUE THREAD

**Issue by fazeelzama20** [mmazzarolo/react-native-login-animation-example#7]
It is showing this error message while running the application on android, it gives same error even on iOS. Please help
It also shown some details as follows
This error is located at: in RCTView (at View.js:113)
in View (at AppContainer.js:102)
in RCTView (at View.js:113)
in View (at AppContainer.js:122)
in AppContainer (at renderApplication.js:34)

**Comment by mmazzarolo** [comment]
Did you cloned the entire project and run it with the dependencies provided in the package.json?
