### ISSUE TITLE
start project

### ISSUE THREAD

**Issue by CNX09** [mmazzarolo/react-native-login-animation-example#8]
hello sir,, im newbie in react native..
i'm already download the project and run the command : 
"npm install"
"npm start"

but the project not start..

how to start the project sir,? thank you

**Comment by mmazzarolo** [comment]
Hello @CNX09, I'm sorry but this is not the right place to answer this kind of questions. 
Please [read the official React-Native documentation](https://facebook.github.io/react-native/docs/getting-started.html) and if you'll still face issues regarding this library feel free to submit a new issue here!
